# Generated by Django 2.2 on 2020-11-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlocation',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='cost_center',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='criticality_reason',
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='criticality_reason',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.DeleteModel(
            name='AssetLocationCostCenter',
        ),
        migrations.DeleteModel(
            name='AssetLocationCriticalityReason',
        ),
    ]
