# Generated by Django 2.2 on 2020-12-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20201130_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_attributes',
            field=models.ManyToManyField(null=True, to='assets.AssetAttribute'),
        ),
    ]
