# Generated by Django 2.2 on 2020-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_asset_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='Bo',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
