# Generated by Django 2.2 on 2020-12-16 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetlocation_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='Assessment_Bill_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Assessment_Bill_Payment_Date',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Connected_to_Location_ID',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Current_Rate_Of_Assesment',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Current_Rate_of_Quit_Rent',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='GisID',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Land_Area_Acre',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Land_Asset_Status',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Land_Ownership_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Lease_Expired_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Plan_As_Built_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Plan_Certified_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Plan_Pre_Computation_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Quit_Rent_Bill_Number',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Quit_Rent_Bill_Payment_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Remarks',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Take_Over_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Take_Over_Date_Source_CCC',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Take_Over_Date_Source_QT11',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='Water_Asset_Category',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
