# Generated by Django 2.2 on 2020-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20201216_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocation',
            name='Lease_Expired_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='Quit_Rent_Bill_Payment_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='Take_Over_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='Take_Over_Date_Source_CCC',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='Take_Over_Date_Source_QT11',
            field=models.DateField(null=True),
        ),
    ]
