# Generated by Django 2.2 on 2020-12-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20201218_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
