# Generated by Django 2.2 on 2021-01-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210108_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='registered_datetime',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='asset',
            name='submitted_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
