# Generated by Django 2.2 on 2021-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20210107_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='registered_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
