# Generated by Django 2.2 on 2021-01-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210107_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='registered_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='submitted_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
