# Generated by Django 2.2 on 2020-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20201203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlocationassetlistservicehistories',
            name='effective_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
