# Generated by Django 2.2 on 2020-12-09 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20201203_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderactivitycompletionassetlocationassetlist',
            name='reading_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
