# Generated by Django 2.2 on 2020-12-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_workorderactivitycompletionassetlocationassetlist_reading_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistoriesquestions',
            old_name='reading_datetime',
            new_name='response_datetime',
        ),
    ]
