# Generated by Django 2.2 on 2020-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20201218_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistoriesquestions',
            name='responseDate',
            field=models.DateField(null=True),
        ),
    ]
