# Generated by Django 2.2 on 2020-12-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20201218_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalreading',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorderactivitycompletion',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='submitted_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
