# Generated by Django 2.2 on 2021-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20210107_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalreading',
            name='asset_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='badge_number',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='current_value',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='initial_value_flag',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='measurent_identifier',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='measurent_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='operationalreading',
            name='owning_organization',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
