apiVersion: apps/v1
kind: Deployment
metadata:
  name: airsel-dev-api-redis
  labels:
    deployment: airsel-dev-api-redis
spec:
  selector:
    matchLabels:
      pod: airsel-dev-api-redis
  replicas: 1
  template:
    metadata:
      labels:
        pod: airsel-dev-api-redis
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 6379